theme: jekyll-theme-midnight
title: "JANL Dubai Trip "
description: "Joselyn, Amitha, Naja, Lina 2023 Dubai Trip"
gitorg: "https://github.com/jm1021/leuck_reunion"
description: "June 1 to July 1 2023"
google_analytics:
